version: '3.8'


services:
  smartshop_db:
    image: mysql:8.0
    container_name: smartshop_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartshopdb
      MYSQL_USER: smartshop
      MYSQL_PASSWORD: smartshop123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

#  app:
#    build: .
#    container_name: smartshop_app
#    restart: always
#    depends_on:
#      smartshop_db:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./src:/app/src
#      - ./pom.xml:/app/pom.xml
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://smartshop_db:3306/smartshopdb?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: smartshop
#      SPRING_DATASOURCE_PASSWORD: smartshop123
#      SPRING_PROFILES_ACTIVE: qa
#
#
volumes:
  db_data:
